services: docker
addons:
  apt:
    packages:
      - python-pip

cache:
  directories:
    - /home/travis/docker/
env:
  global:
    - PACKAGE_NAME=urg_stamped
    - DOCKER_CACHE_TARGET=urg-stamped-test
  matrix:
    - ROS_DISTRO_TARGET=melodic
    - ROS_DISTRO_TARGET=kinetic
    - ROS_DISTRO_TARGET=indigo
branches:
  only:
    - master

before_install:
  - pip install --user gh-pr-comment

install: true

script:
  - docker build
    -t ${DOCKER_CACHE_TARGET}:${ROS_DISTRO_TARGET}
    -f Dockerfile.${ROS_DISTRO_TARGET}
    --pull=true ${TRAVIS_BUILD_DIR} || (gh-pr-comment "[#${TRAVIS_BUILD_NUMBER}] FAILED on ${ROS_DISTRO_TARGET}" "docker build failed"; false)
  - docker run --rm -it
    -e TRAVIS_PULL_REQUEST
    -e TRAVIS_REPO_SLUG
    -e TRAVIS_BOT_GITHUB_TOKEN
    -e GITHUB_API_URL_BASE
    -e TRAVIS_BUILD_NUMBER
    ${DOCKER_CACHE_TARGET}:${ROS_DISTRO_TARGET} /catkin_ws/src/${PACKAGE_NAME}/.travis/test.sh
