dist: bionic
services: docker
language: bash

cache:
  directories:
    - /home/travis/docker/
env:
  global:
    - PACKAGE_NAME=urg_stamped
    - DOCKER_CACHE_TARGET=urg-stamped-test
  matrix:
    - ROS_DISTRO_TARGET=noetic
    - ROS_DISTRO_TARGET=melodic
    - ROS_DISTRO_TARGET=kinetic
branches:
  only:
    - master

before_install:
  - curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s

install: true

script:
  - BUILD_LINK="[[#${TRAVIS_BUILD_NUMBER}](${TRAVIS_BUILD_WEB_URL})]"
  - cp ~/.local/bin/gh-pr-comment .travis/
  - |
    docker build \
      -t ${DOCKER_CACHE_TARGET}:${ROS_DISTRO_TARGET} \
      -f .travis/Dockerfile \
      --build-arg ROS_DISTRO=${ROS_DISTRO_TARGET} \
      --pull=true ${TRAVIS_BUILD_DIR} \
      || (gh-pr-comment "${BUILD_LINK} FAILED on ${ROS_DISTRO_TARGET}" "docker build failed"; false)
  - |
    docker run --rm \
      -e BUILD_LINK=${BUILD_LINK} \
      $(sh <(curl -s https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/env.sh)) \
      ${DOCKER_CACHE_TARGET}:${ROS_DISTRO_TARGET} \
      /catkin_ws/src/${PACKAGE_NAME}/.travis/test.sh

jobs:
  include:
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=kinetic
      before_install: curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=melodic
      before_install: curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
      script: .travis/prerelease_test.sh
    - stage: prerelease-test
      if: head_branch =~ ^release-.*$
      env:
        - ROS_DISTRO_TARGET=noetic
      before_install: curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
      script: .travis/prerelease_test.sh
