sudo: required
services: docker

cache:
  directories:
    - /home/travis/docker/
env:
  global:
    - PACKAGE_NAME=urg_stamped
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.lz4
    - DOCKER_CACHE_TARGETS="${PACKAGE_NAME}:latest"
branches:
  only:
    - master

before_install:
  - .travis/load_cache.sh

install: true

script:
  - docker build -t ${PACKAGE_NAME}:latest --pull=true ${TRAVIS_BUILD_DIR}
  - docker run --rm -it -e TRAVIS_PULL_REQUEST -e TRAVIS_REPO_SLUG -e TRAVIS_BOT_GITHUB_TOKEN -e PACKAGE_NAME ${PACKAGE_NAME}:latest /catkin_ws/src/${PACKAGE_NAME}/.travis/test.sh
  - .travis/save_cache.sh
